### ISSUE TITLE
Importing in node.js / react native

### ISSUE THREAD

**Issue by umakantp** [format-message/format-message#185]
I have react native project and when I import this npm package it throws below error:-

statement i wrote:- import FormatMessage from 'format-message';

```
error: bundling failed: Error: While trying to resolve module `format-message` from file `/home/someusername/exp/myproject/src/gcomponents/Translation/Translation.js`, the package `/home/someusername/exp/myproject/node_modules/format-message/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/home/someusername/exp/myproject/node_modules/format-message/index`. Indeed, none of these files exist:

  * `/home/someusername/exp/myproject/node_modules/format-message/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
  * `/home/someusername/exp/myproject/node_modules/format-message/index/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
    at ResolutionRequest.resolveDependency (/home/someusername/exp/myproject/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:104:15)
    at DependencyGraph.resolveDependency (/home/someusername/exp/myproject/node_modules/metro/src/node-haste/DependencyGraph.js:271:4465)
    at dependencies.map.relativePath (/home/someusername/exp/myproject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:379:19)
    at Array.map (<anonymous>)
    at resolveDependencies (/home/someusername/exp/myproject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:378:16)
    at /home/someusername/exp/myproject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:203:33
    at Generator.next (<anonymous>)
    at step (/home/someusername/exp/myproject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:296:307)
    at /home/someusername/exp/myproject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:296:467
    at <anonymous>

```

**Comment by vanwagonet** [comment]
react-native has it's own module resolver that's different than node. I'm currently working on a RN app at my day job, and we are using format-message without problems. You may need to start up the metro bundler with a flag telling it to clear the cache, though.

Looking closer at your specific error, it looks like you have a file missing. The package.json doesn't have a `main` field, and the package definitely should have an `index.js` file. Could you try reinstalling it?

**Comment by vanwagonet** [comment]
I can't reproduce the issue, and am successfully using format-message in node and react-native.
